spring:
  application.name: payment-processing
  profiles.active: ${ACTIVE_PROFILE:kafka}
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5435}/${DATABASE_NAME:paymentdb}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  liquibase.change-log: classpath:db/changelog-master.yaml
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVER}
    topic: ${KAFKA_TOPIC:payment.change.log}

server:
  port: 8080
  shutdown: graceful
  servlet.context-path: /api/v1

management:
  server.port: 8091
  endpoint:
    health.enabled: true
    info.enabled: true
    prometheus.enabled: true
    metrics.enabled: true
    loggers.enabled: true
  endpoints.web.exposure.include: health,info,prometheus,metrics,loggers

springdoc:
  swagger-ui:
    path: '/swagger-ui'
    disable-swagger-default-url: true

logging:
  level:
    ru.vsu.csf.asashina.paymentprocessing: TRACE

testing:
  entities-amount: ${LOAD_TESTING_ENTITIES_AMOUNT:5_000_000}